# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwmwymacyiE998Psc5p-wDgOeqErsiQ0
"""

"""
2) Correlation and Regression Lines - A Quick Recap #2

Here are the test scores of 10 students in physics and history:

Physics Scores  15  12  8   8   7   7   7   6   5   3
History Scores  10  25  17  11  13  17  20  13  9   15
Compute the slope of the line of regression obtained while treating Physics as the independent variable. Compute the answer correct to three decimal places.

Output Format

In the text box, enter the floating point/decimal value required. Do not leave any leading or trailing spaces. Your answer may look like: 0.255

This is NOT the actual answer - just the format in which you should provide your answer.
"""
# Enter your code here. Read input from STDIN. Print output to STDOUT
X =[15,12,8,8,7,7,7,6,5,3]
Y = [10,25,17,11,13,17,20,13,9,15]

def mean(arr):
  return sum(arr)/len(arr)

x_mean = mean(X)
y_mean = mean(Y)

# slope = Σ(x - mean(x)) * (y - mean(y)) / Σ (x - mean(x))²
xy_sum, xsquare_sum = 0.0, 0.0
for x, y in zip(X, Y):
    xy_sum += (x - x_mean) * (y - y_mean)
    xsquare_sum += (x - x_mean)**2

slope = xy_sum / xsquare_sum
print('{:0.3f}'.format(slope))