# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwmwymacyiE998Psc5p-wDgOeqErsiQ0
"""

"""
Missing Stock Prices

"""
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
from scipy import interpolate    
def calculate_missing(readings, n):
    prices = []
    for i in range(n):
        timestamp, price = readings[i].split('\t')
        prices.append(price)
    
    idx, missing_idx = [], []
    prices_final = []
    # Split missing and available prices indexes
    for i in range(n):
        if "Missing" in prices[i]:
            missing_idx.append(i)
        else:
            idx.append(i)
            prices_final.append(prices[i])
    
    # Spline Interpolation
    spline = interpolate.UnivariateSpline(np.array(idx), np.array(prices_final), s=2)
    for missing in missing_idx:
        print(spline(missing))           
        
if __name__ == '__main__':
    n = int(input().strip())
    readings = []
    for _ in range(n):
        readings_item = input()
        readings.append(readings_item)
    calculate_missing(readings, n)