# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwmwymacyiE998Psc5p-wDgOeqErsiQ0
"""

"""
Day 6: Multiple Linear Regression: Predicting Housing Prices

https://www.hackerrank.com/challenges/predicting-house-prices/problem
"""
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
from sklearn import linear_model

def load_data():
    features, rows = map(int, input().split(' '))
    # Train Data
    data_train = [input().split(' ') for _ in range(rows)]
    data_train = np.array(data_train, dtype=np.float64)   
    X_train, Y_train = data_train[:, 0:features], data_train[:, -1]
    # Train Data
    test_rows = int(input())
    data_test = [input().split(' ') for _ in range(test_rows)]
    X_test = np.array(data_test, dtype=np.float64)
    return X_train, Y_train, X_test

def model(X_train, Y_train, X_test):       
    # Linear Regression Model
    lr_model = linear_model.LinearRegression()
    lr_model.fit(X, Y)
    # Price Prediction
    Y_test = lr_model.predict(X_test)
    for y in Y_test:
        print('{:0.1f}'.format(y))

if __name__ == '__main__':
    X, Y, X_test = load_data()
    model(X, Y, X_test)